version: '3.8'

services:
  finbotaiagent:
    image: finbotaiagent:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finbotaiagent
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    networks:
      - finbot-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/weatherforecast"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  finbot-network:
    driver: bridge
