version: '3.8'

services:
  finbotaiagent:
    image: finbotaiagent:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finbotaiagent
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - finbot-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/weatherforecast"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  finbot-network:
    driver: bridge
    # Auto-assigned subnet by Docker
