name: Deploy to AWS EC2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    
    - name: Test
      run: dotnet test --no-build --verbosity normal

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build application
      run: dotnet build --configuration Release --no-restore
    
    - name: Publish application
      run: dotnet publish --configuration Release --output ./publish
    
    - name: Create deployment package
      run: |
        tar -czf finbotaiagent.tar.gz -C ./publish .
    
    - name: Copy files to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: ${{ secrets.EC2_PORT || 22 }}
        source: "."
        target: "/home/ubuntu/finbotaiagent"
    
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: ${{ secrets.EC2_PORT || 22 }}
        script: |
          # Create deployment directory
          mkdir -p /home/ubuntu/finbotaiagent
          cd /home/ubuntu/finbotaiagent
          
          # Stop existing containers
          docker-compose down || true
          
          # Remove old image
          docker rmi finbotaiagent:latest || true
          
          # Configure PostgreSQL for Docker access
          echo "🗄️ Configuring PostgreSQL for Docker access..."
          sudo sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '*'/" /etc/postgresql/*/main/postgresql.conf
          
          # Add Docker network ranges to pg_hba.conf
          sudo tee -a /etc/postgresql/*/main/pg_hba.conf << 'EOF'
          
          # Allow connections from Docker bridge networks
          host    all             all             172.16.0.0/12           md5
          host    all             all             192.168.0.0/16          md5
          host    all             all             10.0.0.0/8              md5
          EOF
          
          # Restart PostgreSQL
          sudo systemctl restart postgresql
          echo "✅ PostgreSQL configured and restarted"
          
          # Create database user and database
          sudo -u postgres psql -c "CREATE USER ${{ secrets.DB_USERNAME }} WITH PASSWORD '${{ secrets.DB_PASSWORD }}';" 2>/dev/null || echo "User already exists"
          sudo -u postgres psql -c "CREATE DATABASE ${{ secrets.DB_NAME }} OWNER ${{ secrets.DB_USERNAME }};" 2>/dev/null || echo "Database already exists"
          sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE ${{ secrets.DB_NAME }} TO ${{ secrets.DB_USERNAME }};"
          
          # Create expenses table (no seed data)
          sudo -u postgres psql -d ${{ secrets.DB_NAME }} -c "
          CREATE TABLE IF NOT EXISTS expenses (
              id SERIAL PRIMARY KEY,
              employee_id VARCHAR(50) NOT NULL,
              amount DECIMAL(10,2) NOT NULL,
              category VARCHAR(100) NOT NULL,
              description TEXT,
              status VARCHAR(50) DEFAULT 'Pending',
              submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
          );" 2>/dev/null || echo "Table already exists"
          
          echo "✅ Database and user configured"
          
          # Create environment file with EC2 internal IP for maximum reliability
          EC2_INTERNAL_IP=$(hostname -I | awk '{print $1}')
          cat > .env << EOF
          # Database Configuration - Using EC2 Internal IP for reliability
          DB_HOST=$EC2_INTERNAL_IP
          DB_USERNAME=${{ secrets.DB_USERNAME }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DB_NAME=${{ secrets.DB_NAME }}
          
          # Application Configuration
          ASPNETCORE_ENVIRONMENT=Production
          ASPNETCORE_URLS=http://+:8080
          
          # Performance Settings
          ASPNETCORE_Kestrel__Limits__MaxConcurrentConnections=100
          ASPNETCORE_Kestrel__Limits__MaxConcurrentUpgradedConnections=100
          EOF
          
          # Update docker-compose.yml with bridge networking
          cat > docker-compose.yml << 'EOF'
          version: '3.8'
          
          services:
            finbotaiagent:
              image: finbotaiagent:latest
              build:
                context: .
                dockerfile: Dockerfile
              container_name: finbotaiagent
              restart: unless-stopped
              ports:
                - "8080:8080"
              env_file:
                - .env
              networks:
                - finbot-network
              healthcheck:
                test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/weatherforecast"]
                interval: 30s
                timeout: 10s
                retries: 3
                start_period: 40s
              logging:
                driver: "json-file"
                options:
                  max-size: "10m"
                  max-file: "3"
              deploy:
                resources:
                  limits:
                    memory: 512M
                  reservations:
                    memory: 256M
              extra_hosts:
                - "host.docker.internal:host-gateway"
          
          networks:
            finbot-network:
              driver: bridge
              # Auto-assigned subnet by Docker
          EOF
          
          # Build and start containers
          docker-compose build
          docker-compose up -d
          
          # Wait for health check
          sleep 30
          
          # Verify deployment
          if curl -f http://localhost:8080/weatherforecast; then
            echo "Deployment successful!"
          else
            echo "Deployment failed!"
            docker-compose logs
            exit 1
          fi 